### ISSUE TITLE
How to remove the uuid doesn't work

### ISSUE THREAD

**Issue by dFegnoux** [jeffymahoney/loopduplicate.com#3]
Hi Jeffy!

First of all thank you for your module, i'm just here because a friend went to your page http://loopduplicate.com/content/how-to-remove-the-uuid-from-drupal-8-configuration-exports-using-bash and I think there is an error. 

You should have `sed -i '/^uuid:/d' $f`, I don't know if it's a version problem but `sed` will interpret the regexp as the file you want to change.

Does it work for you?

Best regards,

**Comment by jeffymahoney** [comment]
Interesting. The way I have it in the article works for me. I checked the GNU man page and it seems to suggest you can do it either way. By passing an empty string after the -i option, I'm explicitly saying that I don't want to create another file with a different extension (suffix).

If you pass a regex as the first argument, sed apparently recognizes that it's a regex.

https://www.gnu.org/software/sed/manual/sed.txt
